//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must not be null when creating an Action..
        /// </summary>
        internal static string ACTION_TYPE_NULL_ERROR {
            get {
                return ResourceManager.GetString("ACTION_TYPE_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action must not be null when calling Dispatch..
        /// </summary>
        internal static string DISPATCH_ACTION_NULL_ERROR {
            get {
                return ResourceManager.GetString("DISPATCH_ACTION_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================.
        /// </summary>
        internal static string STDOUT_LOGGER_MW_ACTION_SEPARATOR {
            get {
                return ResourceManager.GetString("STDOUT_LOGGER_MW_ACTION_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatching {0}.
        /// </summary>
        internal static string STDOUT_LOGGER_MW_DISPATCHING {
            get {
                return ResourceManager.GetString("STDOUT_LOGGER_MW_DISPATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New State:.
        /// </summary>
        internal static string STDOUT_LOGGER_MW_NEW_STATE {
            get {
                return ResourceManager.GetString("STDOUT_LOGGER_MW_NEW_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not contain the queried type..
        /// </summary>
        internal static string STORE_TYPEPARAM_INCORRECT_ERROR {
            get {
                return ResourceManager.GetString("STORE_TYPEPARAM_INCORRECT_ERROR", resourceCulture);
            }
        }
    }
}
